### PR TITLE
Dockerized site development

### PR DESCRIPTION
**Pull request by mikesir87**
Hello all! Figured I'd reach out and help out a little.

I went ahead and Dockerized this repo to make it easier for others to contribute (feel free to add more to the README). If you haven't played with Docker yet (I highly encourage you to do so), it'll allow folks to contribute without needing to install the Ruby stack, have matching versions, etc.  It's now just a simple command to get up and running and the app is completely isolated from anything else on the machine.  Might not be a bad idea to encourage Docker-izing of the repos that are shared through the org to further encourage collaboration.  Anywho... go ahead and review and let me know what you think!

### CODE REVIEW

**Comment by forteddyt** [comment]
Hey mikesir, to be quite honest neither of us are very familiar with Docker, so we won't make a concrete decision just yet. However, we'll look into it in the coming weeks and then go from there.

**Comment by mikesir87** [comment]
Totally understand. But, figured I'd introduce it to you.  There's a big movement within the IT groups on campus to use Docker in their various applications and is becoming the go-to standard for much of the industry.  I'd be more than happy to meet with you guys on campus sometime and explain everything in-person.  Just look me up and shoot me a note! :)

**Comment by mikesir87** [comment]
Just wanted to follow-up with this and see if there's anything I can do to help you guys out.  Adopting Docker is going to greatly increase the ability for others to collaborate on the various projects.  If you'd like to meet and I can do a demo, just let me know.  I'd be happy to do so.

**Comment by forteddyt** [comment]
Hey, sorry about the delay. Would you be available to meet up with me, Matt (@mpetracca26), and Aaron (@zoto724) on Friday? We're available from 2:30 to 6:30, so any time during that would be ideal for us.

**Comment by mikesir87** [comment]
Normally, yes, I would. But, I'm going to be out-of-town on Friday for a charity event on Saturday. Do you have any availability on Thursday?

**Comment by forteddyt** [comment]
Thursday some time after 5:30 would be fine with us. Do you have a preferred time?

**Comment by mikesir87** [comment]
Sounds good. Just sent you a direct note to coordinate on final time/place.

**Pull request merged**
